### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by alexisdavidson** [stackup-wallet/erc-4337-examples#12]
Hi, I'm getting the following error when using the stackup-wallet/erc-4337-examples package from a React application project context:

Uncaught ReferenceError: Buffer is not defined
at ./node_modules/@account-abstraction/utils/dist/src/ERC4337Utils.js

Looks like it's coming from the @account-abstraction package. Apparently it's a deprecated one. Are there any fixes planned for this?

Everything works fine when calling these examples from this project or another non-React environment

**Comment by hazim-j** [comment]
Hey @alexisdavidson, by default Buffer API is not available within a React (or browser) context. Try doing this and see if it works first.

Install [buffer](https://www.npmjs.com/package/buffer) and add this to your main index.js file

```
import { Buffer } from "buffer";

window.Buffer = window.Buffer || require("buffer").Buffer;
```

**Comment by alexisdavidson** [comment]
Hey @hazim-j thanks for getting back to me. Unfortunately I tried this and the error stays exactly the same in the browser console.

Here are the errors that are shown in the server console that run the app:

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/BaseAccountAPI.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\BaseAccountAPI.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\BaseAccountAPI.ts'

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/DeterministicDeployer.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\DeterministicDeployer.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\DeterministicDeployer.ts'

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/ERC4337EthersProvider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\ERC4337EthersProvider.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\ERC4337EthersProvider.ts'

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/ERC4337EthersSigner.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\ERC4337EthersSigner.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\ERC4337EthersSigner.ts'

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/HttpRpcClient.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\HttpRpcClient.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\HttpRpcClient.ts'

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/PaymasterAPI.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\PaymasterAPI.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\PaymasterAPI.ts'

WARNING in ./node_modules/@account-abstraction/sdk/dist/src/Provider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\Provider.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\sdk\src\Provider.ts'


WARNING in ./node_modules/@account-abstraction/utils/dist/src/Version.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\utils\src\Version.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\utils\src\Version.ts'

WARNING in ./node_modules/@account-abstraction/utils/dist/src/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\utils\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Projects\Blockchain Projects\ERC4337\try\node_modules\@account-abstraction\utils\src\index.ts'

**Comment by alexisdavidson** [comment]
Hi @hazim-j , after creating a fresh Typescript React project and importing erc-4337-examples, I came to receive the next error. I created a git repository for you to check it out: https://github.com/alexisdavidson/erc4337-react

When running "npm run start" everything runs fine. But once you uncomment the lines in the App.tsx: main() function then the following errors appear:




ERROR in ./node_modules/erc-4337-examples/src/getGasFee.ts 4:0
Module parse failed: The keyword 'interface' is reserved (4:0)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| import { JsonRpcProvider } from "@ethersproject/providers";
| 
> interface Gas {
|   maxFeePerGas: BigNumberish;
|   maxPriorityFeePerGas: BigNumberish;

ERROR in ./node_modules/erc-4337-examples/src/getHttpRpcClient.ts 5:10
Module parse failed: Unexpected token (5:10)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| 
| export async function getHttpRpcClient(
>   provider: JsonRpcProvider,
|   bundlerUrl: string,
|   entryPointAddress: string

ERROR in ./node_modules/erc-4337-examples/src/getSimpleAccount.ts 6:10
Module parse failed: Unexpected token (6:10)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Failed to compile.

Module parse failed: The keyword 'interface' is reserved (4:0)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| import { JsonRpcProvider } from "@ethersproject/providers";
|
> interface Gas {
|   maxFeePerGas: BigNumberish;
|   maxPriorityFeePerGas: BigNumberish;
WARNING in [eslint]
src\App.tsx
  Line 14:7:  'helloWorld' is assigned a value but never used  @typescript-eslint/no-unused-vars

ERROR in ./node_modules/erc-4337-examples/src/getGasFee.ts 4:0
Module parse failed: The keyword 'interface' is reserved (4:0)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| import { JsonRpcProvider } from "@ethersproject/providers";
| 
> interface Gas {
|   maxFeePerGas: BigNumberish;
|   maxPriorityFeePerGas: BigNumberish;

ERROR in ./node_modules/erc-4337-examples/src/getHttpRpcClient.ts 5:10
Module parse failed: Unexpected token (5:10)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| 
| export async function getHttpRpcClient(
>   provider: JsonRpcProvider,
|   bundlerUrl: string,
|   entryPointAddress: string

ERROR in ./node_modules/erc-4337-examples/src/getSimpleAccount.ts 6:10
Module parse failed: Unexpected token (6:10)
File was processed with these loaders:

**Comment by JohnRising** [comment]
Hey @alexisdavidson! Just following up on our conversation offline. Are you using a bundler like Webpack or Parcel? This will allow you to use the buffer package as a dependency in your application, and the bundler will handle including it in the bundled code that is delivered to the browser.

**Comment by alexisdavidson** [comment]
Hi @JohnRising thanks for this. I could get rid of the buffer error by polyfilling buffer in the webpack config. Now everything runs correctly from a React client environment.
